repos:
 - repo: https://github.com/PyCQA/isort
 rev: "5.13.2"
 hooks:
 - id: isort
 args: [--check-only, --diff]

 - repo: https://github.com/astral-sh/ruff-pre-commit
 rev: "v0.4.4"
 hooks:
 - id: ruff
 args: [--select, F401]

 - repo: local
 hooks:
 - id: precommit-hook-agent
 name: Pre-commit Hook Agent
 entry: python precommit_hook/precommit_hook.py
 language: python
 types: [python]
 pass_filenames: false
 stages: [pre-commit]
